# local cassandra for development
cassandra:
  defaultQueryConsistency: ONE
  defaultUpdateConsistency: ONE
  updateTimeoutMillis: 5000
  compression: LZ4
  nodeAddress: cassandra-oem.service.consul

  keyspaces:
    - name: event_ledger
      createCommand: "CREATE KEYSPACE testkeyspace WITH replication = {'class':'SimpleStrategy', 'replication_factor':1};"
      dropCommand: "DROP KEYSPACE IF EXISTS testkeyspace;"
      tables:
        - name: calls
          createCommand: >
              CREATE TABLE testkeyspace.rt911 (
                address varchar,
                calltype varchar,
                calltime varchar,
                latitude varchar,
                longitude varchar,
                location varchar,
                id varchar PRIMARY KEY);

---
spring.profiles: local

cassandra.nodeAddress: localhost

spring.application.name: rt911
spring.application.environment: local

---
s3.bucket.name: test-bucket-1
s3.url: "s3://peoplenet-spark-poc-data/data/*"

cassandra.keyspace.name: testkeyspace
cassandra.host: 127.0.0.1
